SEED: 1337  # random seed for reproduce results

RUN_NAME: 'EXP198-IR_MV_50_MSCELEB-BFFC1033-MA12345-ArcFace-FocalLoss-epochs0-batch16'  # experiment_name
DATA_ROOT: '/home/gustav/dataset9'  # the parent data root
TRAIN_SET: 'rgb_bff_crop'  # train dataset name

MODEL_ROOT: './model'  # the root to buffer checkpoints
LOG_ROOT: './log'  # the root to log
BACKBONE_RESUME_ROOT: '/home/gustav/HM_IDENT_3DFR/pretrained/backbone_ir50_ms1m_epoch63.pth' #backbone_ir50_asia.pth'# the root to resume training from a saved checkpoint
HEAD_RESUME_ROOT: ''  # the root to resume training from a saved checkpoint
TRAIN_ALL: False
USE_FACE_CORR: False
BACKBONE_NAME: 'IR_MV_50'
AGG:
  AGG_NAME: 'MeanAggregator'
  AGG_CONFIG: []
HEAD_NAME: 'ArcFace'  # support:  ['Softmax', 'ArcFace', 'CosFace', 'SphereFace', 'Am_softmax']
LOSS_NAME: 'Focal'  # support: ['Focal', 'Softmax']

INPUT_SIZE: [112, 112]  # support: [112, 112] and [224, 224]
NUM_VIEWS: 25
RGB_MEAN: [0.5, 0.5, 0.5]  # for normalize inputs to [-1, 1]
RGB_STD: [0.5, 0.5, 0.5]
EMBEDDING_SIZE: 512  # feature dimension
BATCH_SIZE: 16  # batch size
DROP_LAST: true  # whether drop the last batch to ensure consistent batch_norm statistics
LR: 0.001  # initial LR
NUM_EPOCH: 1  # total epoch number (use the first 1/25 epochs to warm up)
PATIENCE: 100  # patience for early stopping
WEIGHT_DECAY: 0.0005  # do not apply to batch_norm parameters
MOMENTUM: 0.3
STAGES: [50, 75, 95]  # epoch stages to decay learning rate

MULTI_GPU: true
# flag to use multiple GPUs; if you choose to train with single GPU, you should first run "export CUDA_VISILE_DEVICES=device_id" to specify the GPU card you want to use
GPU_ID: [0]  # specify your GPU ids
PIN_MEMORY: true
NUM_WORKERS: 8